name: pynorms
on: [push, pull_request, workflow_dispatch]

jobs:
  check_norms:
    runs-on: ubuntu-latest
    name: Check Python coding norms

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0
